PRAGMA foreign_keys = ON;

-- 課題その2 用：作問しやすいミニDB（大学の履修・成績）

DROP TABLE IF EXISTS "履修";
DROP TABLE IF EXISTS "科目";
DROP TABLE IF EXISTS "学生";
DROP TABLE IF EXISTS "教員";
DROP TABLE IF EXISTS "学科";

CREATE TABLE "学科" (
  "学科ID"   TEXT PRIMARY KEY,
  "学科名"   TEXT NOT NULL UNIQUE
);

CREATE TABLE "教員" (
  "教員ID"   INTEGER PRIMARY KEY,
  "氏名"     TEXT NOT NULL,
  "学科ID"   TEXT NOT NULL,
  FOREIGN KEY ("学科ID") REFERENCES "学科" ("学科ID")
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE "学生" (
  "学籍番号" INTEGER PRIMARY KEY,
  "氏名"     TEXT NOT NULL,
  "学年"     INTEGER NOT NULL CHECK ("学年" BETWEEN 1 AND 4),
  "学科ID"   TEXT NOT NULL,
  FOREIGN KEY ("学科ID") REFERENCES "学科" ("学科ID")
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE "科目" (
  "科目ID"   TEXT PRIMARY KEY,
  "科目名"   TEXT NOT NULL,
  "単位"     INTEGER NOT NULL CHECK ("単位" >= 1),
  "学科ID"   TEXT NOT NULL,
  "担当教員ID" INTEGER NOT NULL,
  FOREIGN KEY ("学科ID") REFERENCES "学科" ("学科ID")
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY ("担当教員ID") REFERENCES "教員" ("教員ID")
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE "履修" (
  "履修ID"   INTEGER PRIMARY KEY,
  "学籍番号" INTEGER NOT NULL,
  "科目ID"   TEXT NOT NULL,
  "点数"     INTEGER NOT NULL CHECK ("点数" BETWEEN 0 AND 100),
  FOREIGN KEY ("学籍番号") REFERENCES "学生" ("学籍番号")
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY ("科目ID") REFERENCES "科目" ("科目ID")
    ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE ("学籍番号", "科目ID")
);


